### ISSUE TITLE
When using 1 or more vpc_ids in secondary_vpcs, running the same module multiple times results in changes in breaking changes

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-private-route53-zone#12]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you are interested in working on this issue or have submitted a pull request, please leave a comment!***

***

### Summary
See https://www.terraform.io/docs/providers/aws/r/route53_zone.html#private-zone

The recommendation when using both `vpc.vpc_id` and `aws_route53_zone_association` is to ignore lifecycle changes to `vpc`. If this is not ignored, running a completed stack using this module will result in the primary vpc_id being removed even if there are no changes to the stack.

### Module Version
v0.3.0

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.11.14
+ provider.aws v2.44.0
```

### Affected Resource(s)

* aws_route53_zone
* aws_route53_zone_association

### Terraform Configuration Files

```hcl
module "private_route53_hosted_zone" {
  source = "git@github.com:traveloka/terraform-aws-private-route53-zone.git?ref=v0.3.0"

  environment    = "${var.environment}"
  product_domain = "${var.product_domain}"

  name = "${local.private_domain}"

  main_vpc       = "${data.terraform_remote_state.main_vpc.vpc_id}"
  secondary_vpcs = ["${data.terraform_remote_state.secondary_vpcs.*.vpc_id}"]
}
```

### Expected Behavior

Running the same stack without changing any config should result in no changes

### Actual Behavior

Running the same stack without changing any config will result in the primary vpc_id being removed.

### Screenshots

```
Terraform will perform the following actions:

  ~ aws_route53_zone.main
      vpc.#:                 "2" => "1"
      vpc.2050750915.vpc_id: "vpc-03fcb8d9363548f31" => ""
      vpc.4149907530.vpc_id: "vpc-0a029e7e5c4d6251d" => "vpc-0a029e7e5c4d6251d"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

* #0000

**Comment by isen-ng** [comment]
It seems to me that there are 2 ways to solve this.

### Method 1

Ignore lifecycle changes to `vpc` block. This means that the main vpc can never change.

```
  lifecycle {
    ignore_changes = ["vpc"]
  }
```

### Method 2

Do not use `aws_route53_zone_association`. Instead use multiple vpc blocks.

```
  vpc = {
    vpc_id = "${var.main_vpc}"
  }
  vpc = "${var.secondary_vpcs}"
```

The downside is that the `secondary_vpcs` must be populated like this:

```
secondary_vpcs = [{
   vpc_id = "my_vpc_id_1"
}, {
   vpc_id = "my_vpc_id_2"
}]
```

**Comment by sshvetsov** [comment]
Thank you for opening this issue and documenting the details of this bug @isen-ng.

Since it's common for a single private hosted zone to be associated with multiple VPCs, it's also likely that such associations may be created using `aws_route53_zone_association` resource _outside_ of this module. Ideally, we should avoid using `vpc { vpc_id = "vpc-XXXXX" }` block entirely and use only `aws_route53_zone_association` resource to associate primary and other VPCs to the hosted zone. However, I don't believe it's possible to avoid use of `vpc` block inside the private `aws_route53_zone` configuration, since private hosted zone _cannot_ be created _without_ VPC association. Since we cannot use `count` with `vpc` block, but there's a good chance someone might need to attach variable number of VPCs to a given zone (e.g. during cross-account migration, during Transit Gateway or VPC peering), using multiple `vpc` blocks doesn't seem to be a viable options in Terraform v0.11. This leaves us with `lifecycle { ignore_changes =  ["vpc"] }` as the only feasible option.

Perhaps to be sure, we should try creating a private hosted zone and associate primary VPC using `aws_route53_zone_association` resource. If that works, we should drop the `vpc` block entirely.

If that doesn't work and we have to use `lifecycle` block, will primary VPC association still be removed from the state file? If so, we should also create an additional `aws_route53_zone_association` resource for the primary VPC to prevent it from being removed from the state file when secondary associations are added.

@traveloka/techops can I get your thoughts on this?

**Comment by isen-ng** [comment]
> Perhaps to be sure, we should try creating a private hosted zone and associate primary VPC using aws_route53_zone_association resource. If that works, we should drop the vpc block entirely.

This does not work. I have tested this already. 

If you create a hosted zone without a vpc block, it will automatically become a public hosted zone. You cannot create a private hosted zone without at least 1 vpc block. Not in terraform, not in AWS console, not in AWS cli...

**Comment by sshvetsov** [comment]
OK, so then only concern is the situation where primary VPC needs to be changed and user updates the value of the `main_vpc` variable:
https://github.com/traveloka/terraform-aws-private-route53-zone/blob/f191d933503a790c1094d93f52794f5c644e8b15/variables.tf#L16-L19

User would expect detachment of the private zone from the `main_vpc` and attachment to a new VPC provided by the variable. However, that will not happen if we add `lifecycle` block.

We might have to also use `aws_route53_zone_association` to attach private zone to the primary VPC and rely on `vpc` block purely for the initial creation of the private zone.

Thoughts?

**Comment by sshvetsov** [comment]
@traveloka/site-infra would love your perspective on this as well.

**Comment by isen-ng** [comment]
> We might have to also use aws_route53_zone_association to attach private zone to the primary VPC and rely on vpc block purely for the initial creation of the private zone.

This is something I have not tried. I will see if I could test this.

**Comment by isen-ng** [comment]
> We might have to also use aws_route53_zone_association to attach private zone to the primary VPC and rely on vpc block purely for the initial creation of the private zone.

I just tested this and I could not get it to work.

If I did this:

```hcl
resource "aws_route53_zone" "main" {
  name = "${var.name}"

  vpc {
  }

  comment       = "${local.description}"
  force_destroy = "${var.force_destroy}"

  tags = {
    "Name"          = "${var.name}"
    "ProductDomain" = "${var.product_domain}"
    "Environment"   = "${var.environment}"
    "Description"   = "${local.description}"
    "ManagedBy"     = "${local.managed_by}"
  }
}
```

It would complain that `vpc.0.vpc_id` is required.

If I did this:

```hcl
resource "aws_route53_zone" "main" {
  name = "${var.name}"

  lifecycle {
    ignore_changes = ["vpc"]
  }

  vpc {
    vpc_id = "${var.main_vpc}"
  }

  comment       = "${local.description}"
  force_destroy = "${var.force_destroy}"

  tags = {
    "Name"          = "${var.name}"
    "ProductDomain" = "${var.product_domain}"
    "Environment"   = "${var.environment}"
    "Description"   = "${local.description}"
    "ManagedBy"     = "${local.managed_by}"
  }
}

resource "aws_route53_zone_association" "primary" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  vpc_id  = "${var.main_vpc}"
}

resource "aws_route53_zone_association" "secondary" {
  count   = "${length(var.secondary_vpcs)}"
  zone_id = "${aws_route53_zone.main.zone_id}"
  vpc_id  = "${var.secondary_vpcs[count.index]}"
}
```

It would complain that the main vpc is already associated to the hosted zone ...

**Comment by sshvetsov** [comment]
Grr... Looks like a "two-part apply" type of problem. I'm gonna need to think more about it.
